services:
  caddy:
    container_name: caddy
    image: caddy:2
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-config:/config
      - ./caddy-data:/data
    networks:
      - reverse-proxy-network
    environment:
      - VW_DOMAIN=$VW_DOMAIN
      - VW_EMAIL=$VW_EMAIL
      - VW_LOG=$VW_LOG
      - WP1_DOMAIN=$WP1_DOMAIN
      - WP1_EMAIL=$WP1_EMAIL
      - WP1_LOG=$WP1_LOG
      - NAS_DOMAIN=$NAS_DOMAIN
      - NAS_EMAIL=$NAS_EMAIL
      - NAS_LOG=$NAS_LOG

networks:
  reverse-proxy-network:
    external: true